### ISSUE TITLE
onnx 模型转换问题

### ISSUE THREAD

**Issue by SJDai-375** [MegEngine/mgeconvert#101]
WARNING: The argument `dynamic_input_shape=True` is not needed any more, onnxsim
can now support dynamic input shapes natively, please refer to the latest 
documentation. An error will be raised in the future.

![image](https://user-images.githubusercontent.com/98135989/193031244-8b3676af-2764-40e8-bdc8-ebfb0acd7520.png)

**Comment by MachineGunLin** [comment]
onnx2mge 目前还不支持 ConvTranspose 算子

**Comment by SJDai-375** [comment]
> onnx2mge 目前还不支持 ConvTranspose 算子

![image](https://user-images.githubusercontent.com/98135989/194683659-7ca31794-e917-4829-97f2-b6fcef0e5865.png)
这里的支持指的是？

**Comment by CaoWGG** [comment]
@SJDai-375 这张表指的是 TracedModule -> {onnx, tflite, caffe} 支持的 op。

onnx -> mge 支持的 op 在这张[表](https://github.com/MegEngine/mgeconvert#onnx---tracedmodule-mge)里。
