### ISSUE TITLE
找不到cuda_fp16.h

### ISSUE THREAD

**Issue by nicheng0019** [MegEngine/mgeconvert#107]
mgeconvert1.0.2版本，onnx模型转mge，报错：

05 09:32:46[mgb] ERR error occurred in computing sequence; synchronizing all comp nodes and releasing vars now ...
RuntimeError: nvrtc compile error: default_program(2): catastrophic error: cannot open source file "cuda_fp16.h"

系统里cuda_fp16.h在/usr/local/cuda-10.1/targets/x86_64-linux/include 这个目录下，请问要如何设置能让mgeconvert找到这个头文件？

**Comment by daisycx** [comment]
请问您是安装的什么版本megengine呢，这个问题在megengine 1.12.0中修复了，请升级版本试试

**Comment by nicheng0019** [comment]
> 请问您是安装的什么版本megengine呢，这个问题在megengine 1.12.0中修复了，请升级版本试试

我用的是1.10.0版本，我升级到1.12.0试试，多谢！
