### ISSUE TITLE
是否有计划提供其他框架到MegEngine的转换器

### ISSUE THREAD

**Issue by lq0104** [MegEngine/mgeconvert#14]
如题，方便使用MegEngine实现推理部署端的加速

**Comment by lixiangyin666** [comment]
目前您有哪些框架需要转到MegEngine呢？
如果是PyTorch则会比较方便，因为MegEngine和PyTorch都是动态训练，接口也类似，代码和参数迁移也方便，迁移完成后调用MegEngine的JIT trace即可dump出可部署的MegEngine模型。
由于mgeconvert和MegEngine已经开源，热烈欢迎您贡献代码
