### ISSUE TITLE
是否支持多输入多输出的mge到onnx转化

### ISSUE THREAD

**Issue by doudoublues** [MegEngine/mgeconvert#30]
是否支持多输入多输出的mge到onnx转化

**Comment by dc3671** [comment]
应该是支持的，你可以指定一下output_spec为你mge dump时output的name，如果有问题可以再反馈

**Comment by doudoublues** [comment]
目前发现F.conv2d在对两个feature map做卷积时候会出现转换分支消失的问题。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MegEngine/mgeconvert"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月9日(星期四) 下午3:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MegEngine/mgeconvert] 是否支持多输入多输出的mge到onnx转化 (#30)





 
应该是支持的，你可以指定一下output_spec为你mge dump时output的name，如果有问题可以再反馈
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dc3671** [comment]
@doudoublues 求一个最小复现

**Comment by doudoublues** [comment]
在论坛上提交了帖子和代码




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MegEngine/mgeconvert"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月9日(星期四) 下午5:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MegEngine/mgeconvert] 是否支持多输入多输出的mge到onnx转化 (#30)





 
@doudoublues 求一个最小复现
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MegChai** [comment]
> 在论坛上提交了帖子和代码

链接：https://discuss.megengine.org.cn/t/topic/1068

**Comment by doudoublues** [comment]
是的 是这个，好像代码因为markdown有点问题。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MegEngine/mgeconvert"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月9日(星期四) 下午5:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MegEngine/mgeconvert] 是否支持多输入多输出的mge到onnx转化 (#30)





  
在论坛上提交了帖子和代码
  
链接：https://discuss.megengine.org.cn/t/topic/1068
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
