### ISSUE TITLE
执行convert mge_to_onnx  ... 报错

### ISSUE THREAD

**Issue by Yaoxingtian** [MegEngine/mgeconvert#73]
你好！
如题，报错如下：
convert: error: invalid choice: 'mge_to_onnx' (choose from 'onnx')
但是convert onnx ... 却可以， 请问知道是什么原因吗 ？
谢谢

**Comment by daisycx** [comment]
请问您使用的mgeconvert版本是多少，以及求发一下转换命令

**Comment by Yaoxingtian** [comment]
> 
mgeconvert版本1.8.2
命令如下：
convert mge_to_onnx -i ./crestereo_eth3d.mge -o ./crestereo_eth3d.onnx --opset 12

**Comment by daisycx** [comment]
1.8.2 应该是megengine的版本，您再看下mgeconvert的版本呢

**Comment by daisycx** [comment]
convert onnx.. 是v0.4.2的用法，convert mge_to_onnx 的用法需要v0.5.0及以上，先看下是不是版本的原因

**Comment by Yaoxingtian** [comment]
> convert onnx.. 是v0.4.2的用法，convert mge_to_onnx 的用法需要v0.5.0及以上，先看下是不是版本的原因

我换了mgeconvert-0.7.0.dev0 没有报这个错了，但是我的模型是双输入的，请问可以转换过来吗？

**Comment by daisycx** [comment]
> 

可以的

**Comment by Yaoxingtian** [comment]
> 但是我的模型是双输入的

请问执行命令是什么？ 谢谢

**Comment by daisycx** [comment]
> convert mge_to_onnx -i ./crestereo_eth3d.mge -o ./crestereo_eth3d.onnx --opset 12

**Comment by daisycx** [comment]
> > 但是我的模型是双输入的
> 
> 请问执行命令是什么？ 谢谢

convert mge_to_onnx -i ./crestereo_eth3d.mge -o ./crestereo_eth3d.onnx --opset 12
